### ISSUE TITLE
can't update 403 error

### ISSUE THREAD

**Issue by barshai** [tiliado/tiliado-repositories#6]
Hi,
Trying to update with linux mint update center.

Gets this error:
W: Failed to fetch https://tiliado.eu/nuvolaplayer/repository/deb/pool/devel/d/diorite/libdiorite0.3_0.3.0~201512301553.57287c9-0+1~trusty_amd64.deb
  HttpError403

W: Failed to fetch https://tiliado.eu/nuvolaplayer/repository/deb/pool/devel/n/nuvolaplayer3/nuvolaplayer3_3.1.0~201512301807.d865d68-0+1~trusty_amd64.deb
  HttpError403

**Comment by jiri-janousek** [comment]
Hello @barshai. Since the release of Nuvola Player 3.0 Stable, the **Nuvola Player 3.1 Rolling Releases repository** requires authentication with a Tiliado account. You can do it with [Tiliado Repository Installer](https://tiliado.github.io/nuvolaplayer/documentation/3.0/install.html#add-nuvola-player-repository) or [manually](https://tiliado.eu/nuvolaplayer/repository/#repository-authentication). Alternatively, you can switch to the **Nuvola Player 3.0 Stable Releases repository**, which doesn't require authentication.
